/*
 * Copyright 2017 Google Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

partial interface VRDisplay {
  sequence<VRHit> hitTest(float x, float y);
  sequence<VRPlane> getPlanes();
  VRAnchor addAnchor(sequence<float> modelMatrix);
  VRAnchor addAnchor(Float32Array modelMatrix);
  void removeAnchor(VRAnchor anchor);
  sequence<VRAnchor> getAnchors();
  sequence<VRMarker> getMarkers(long type, float size);
  const long MARKER_TYPE_AR       = 0x01;
  const long MARKER_TYPE_QRCODE   = 0x02;
};

partial interface VRDisplayCapabilities {
  readonly attribute boolean hasPassThroughCamera;
};

interface VRHit {
  readonly attribute Float32Array modelMatrix;
};

interface VRPlane {
  readonly attribute long identifier;
  readonly attribute Float32Array? modelMatrix;
  readonly attribute Float32Array? extent;
  readonly attribute Float32Array? vertices;
};

[
  Constructor(DOMString type, optional VRPlaneEventInit eventInitDict),
] interface VRPlaneEvent : Event {
  readonly attribute VRDisplay display;
  readonly attribute sequence<VRPlane> planes;
};

dictionary VRPlaneEventInit : EventInit {
  VRDisplay? display;
  sequence<VRPlane> planes;
};

interface VRAnchor {
  readonly attribute long identifier;
  readonly attribute Float32Array? modelMatrix;
};

[
  Constructor(DOMString type, optional VRAnchorEventInit eventInitDict),
] interface VRanchorEvent : Event {
  readonly attribute VRDisplay display;
  readonly attribute sequence<VRAnchor> anchors;
};

dictionary VRAnchorEventInit : EventInit {
  VRDisplay? display;
  sequence<VRAnchor> anchors;
};

interface VRMarker {
  readonly attribute long type;
  readonly attribute long id;
  readonly attribute DOMString content;
  readonly attribute Float32Array modelMatrix;
};
